---
    pool: Default

    trigger: none
   
    pr:
      - main

    steps:
      - script: echo "hello world"
        displayName: 'run the "hello world"'
      - script: echo "my name is venkatesh"
        displayName: "dispaly my name" 


        