# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#  find the sum of the even-valued terms.

first_number = 1
second_number = 2
max_value = int(input("Enter a value: "))
even_sum_value = 0

while first_number <= max_value:
    print(first_number)
    if first_number % 2 == 0:
        even_sum_value = even_sum_value + first_number
    next_number = first_number + second_number
    first_number = second_number
    second_number = next_number
print("sum of the even value: ", even_sum_value)
